import * as Lucide from 'lucide-react'

const iconMap = {
  users: Lucide.Users,
  bookOpen: Lucide.BookOpen,
  user: Lucide.User,
  barChart: Lucide.BarChart,
  layoutDashboard: Lucide.LayoutDashboard,
  userPlus: Lucide.UserPlus,
  userCheck: Lucide.UserCheck,
  userMinus: Lucide.UserMinus,
  refreshCw: Lucide.RefreshCw,
  download: Lucide.Download,
  upload: Lucide.Upload,
  search: Lucide.Search,
  filter: Lucide.Filter,
  edit: Lucide.Edit,
  trash: Lucide.Trash2,
  plus: Lucide.Plus,
  save: Lucide.Save,
  x: Lucide.X,
  check: Lucide.Check,
  chevronDown: Lucide.ChevronDown,
  chevronUp: Lucide.ChevronUp,
  chevronLeft: Lucide.ChevronLeft,
  chevronRight: Lucide.ChevronRight,
  arrowLeft: Lucide.ArrowLeft,
  arrowRight: Lucide.ArrowRight,
  logOut: Lucide.LogOut,
  logIn: Lucide.LogIn,
  userCog: Lucide.UserCog,
  shield: Lucide.Shield,
  bookOpenText: Lucide.BookOpenText,
  graduationCap: Lucide.GraduationCap,
  fileSpreadsheet: Lucide.FileSpreadsheet,
  fileText: Lucide.FileText,
  calculator: Lucide.Calculator,
  barChart2: Lucide.BarChart2,
  pieChart: Lucide.PieChart,
  activity: Lucide.Activity,
  settings: Lucide.Settings,
  lock: Lucide.Lock,
  unlock: Lucide.Unlock,
  key: Lucide.Key,
  eye: Lucide.Eye,
  eyeOff: Lucide.EyeOff,
  mail: Lucide.Mail,
  phone: Lucide.Phone,
  mapPin: Lucide.MapPin,
  calendar: Lucide.Calendar,
  clock: Lucide.Clock,
  alertCircle: Lucide.AlertCircle,
  checkCircle: Lucide.CheckCircle,
  xCircle: Lucide.XCircle,
  info: Lucide.Info,
  helpCircle: Lucide.HelpCircle,
  menu: Lucide.Menu,
  sun: Lucide.Sun,
  moon: Lucide.Moon,
  grid: Lucide.Grid,
  list: Lucide.List,
  home: Lucide.Home,
  building: Lucide.Building,
  building2: Lucide.Building2,
  university: Lucide.University,
  briefcase: Lucide.Briefcase,
  award: Lucide.Award,
  target: Lucide.Target,
  trendingUp: Lucide.TrendingUp,
  trendingDown: Lucide.TrendingDown,
  refreshCcw: Lucide.RefreshCcw,
  moreHorizontal: Lucide.MoreHorizontal,
  moreVertical: Lucide.MoreVertical,
}

export default function Icon({ name, size = 20, className = '', ...props }) {
  const Component = iconMap[name]
  if (!Component) {
    console.warn(`Icon "${name}" not found in iconMap`)
    return null
  }
  return <Component size={size} className={className} {...props} />
}